// Code generated by MockGen. DO NOT EDIT.
// Source: vehicle/vehicle.go
//
// Generated by this command:
//
//	mockgen -source=vehicle/vehicle.go -destination=internal/mocks/vehicle/vehicle.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vehicle "github.com/LucasMateus-eng/operations-service/vehicle"
	gomock "go.uber.org/mock/gomock"
)

// MockReading is a mock of Reading interface.
type MockReading struct {
	ctrl     *gomock.Controller
	recorder *MockReadingMockRecorder
}

// MockReadingMockRecorder is the mock recorder for MockReading.
type MockReadingMockRecorder struct {
	mock *MockReading
}

// NewMockReading creates a new mock instance.
func NewMockReading(ctrl *gomock.Controller) *MockReading {
	mock := &MockReading{ctrl: ctrl}
	mock.recorder = &MockReadingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReading) EXPECT() *MockReadingMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockReading) GetByID(ctx context.Context, id int64) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReadingMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReading)(nil).GetByID), ctx, id)
}

// GetByPlate mocks base method.
func (m *MockReading) GetByPlate(ctx context.Context, plate string) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPlate", ctx, plate)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPlate indicates an expected call of GetByPlate.
func (mr *MockReadingMockRecorder) GetByPlate(ctx, plate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPlate", reflect.TypeOf((*MockReading)(nil).GetByPlate), ctx, plate)
}

// GetByRenavam mocks base method.
func (m *MockReading) GetByRenavam(ctx context.Context, renavam string) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRenavam", ctx, renavam)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRenavam indicates an expected call of GetByRenavam.
func (mr *MockReadingMockRecorder) GetByRenavam(ctx, renavam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRenavam", reflect.TypeOf((*MockReading)(nil).GetByRenavam), ctx, renavam)
}

// List mocks base method.
func (m *MockReading) List(ctx context.Context, specification *vehicle.VehicleSpectification) (*[]vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, specification)
	ret0, _ := ret[0].(*[]vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockReadingMockRecorder) List(ctx, specification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReading)(nil).List), ctx, specification)
}

// MockWriting is a mock of Writing interface.
type MockWriting struct {
	ctrl     *gomock.Controller
	recorder *MockWritingMockRecorder
}

// MockWritingMockRecorder is the mock recorder for MockWriting.
type MockWritingMockRecorder struct {
	mock *MockWriting
}

// NewMockWriting creates a new mock instance.
func NewMockWriting(ctrl *gomock.Controller) *MockWriting {
	mock := &MockWriting{ctrl: ctrl}
	mock.recorder = &MockWritingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriting) EXPECT() *MockWritingMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWriting) Create(ctx context.Context, v *vehicle.Vehicle) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, v)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWritingMockRecorder) Create(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWriting)(nil).Create), ctx, v)
}

// Delete mocks base method.
func (m *MockWriting) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWritingMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWriting)(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MockWriting) Update(ctx context.Context, v *vehicle.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWritingMockRecorder) Update(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWriting)(nil).Update), ctx, v)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, v *vehicle.Vehicle) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, v)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, v)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id int64) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetByPlate mocks base method.
func (m *MockRepository) GetByPlate(ctx context.Context, plate string) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPlate", ctx, plate)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPlate indicates an expected call of GetByPlate.
func (mr *MockRepositoryMockRecorder) GetByPlate(ctx, plate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPlate", reflect.TypeOf((*MockRepository)(nil).GetByPlate), ctx, plate)
}

// GetByRenavam mocks base method.
func (m *MockRepository) GetByRenavam(ctx context.Context, renavam string) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRenavam", ctx, renavam)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRenavam indicates an expected call of GetByRenavam.
func (mr *MockRepositoryMockRecorder) GetByRenavam(ctx, renavam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRenavam", reflect.TypeOf((*MockRepository)(nil).GetByRenavam), ctx, renavam)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, specification *vehicle.VehicleSpectification) (*[]vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, specification)
	ret0, _ := ret[0].(*[]vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, specification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, specification)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, v *vehicle.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, v)
}

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUseCase) Create(ctx context.Context, v *vehicle.Vehicle) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, v)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUseCaseMockRecorder) Create(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUseCase)(nil).Create), ctx, v)
}

// Delete mocks base method.
func (m *MockUseCase) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockUseCase) GetByID(ctx context.Context, id int64) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUseCase)(nil).GetByID), ctx, id)
}

// GetByPlate mocks base method.
func (m *MockUseCase) GetByPlate(ctx context.Context, plate string) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPlate", ctx, plate)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPlate indicates an expected call of GetByPlate.
func (mr *MockUseCaseMockRecorder) GetByPlate(ctx, plate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPlate", reflect.TypeOf((*MockUseCase)(nil).GetByPlate), ctx, plate)
}

// GetByRenavam mocks base method.
func (m *MockUseCase) GetByRenavam(ctx context.Context, renavam string) (*vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRenavam", ctx, renavam)
	ret0, _ := ret[0].(*vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRenavam indicates an expected call of GetByRenavam.
func (mr *MockUseCaseMockRecorder) GetByRenavam(ctx, renavam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRenavam", reflect.TypeOf((*MockUseCase)(nil).GetByRenavam), ctx, renavam)
}

// List mocks base method.
func (m *MockUseCase) List(ctx context.Context, specification *vehicle.VehicleSpectification) (*[]vehicle.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, specification)
	ret0, _ := ret[0].(*[]vehicle.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUseCaseMockRecorder) List(ctx, specification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUseCase)(nil).List), ctx, specification)
}

// Update mocks base method.
func (m *MockUseCase) Update(ctx context.Context, v *vehicle.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUseCaseMockRecorder) Update(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUseCase)(nil).Update), ctx, v)
}
